require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'SpPortal' do
  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios'
  use_react_native!(:path => config["reactNativePath"])
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'



  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  pod 'react-native-simple-toast', :path => '../node_modules/react-native-simple-toast'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils', '~> 3.10.3'

  
  target 'SpPortalTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'SpPortal-tvOS' do
  # Pods for SpPortal-tvOS

  target 'SpPortal-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
